### ISSUE TITLE
test_image.py error

### ISSUE THREAD

**Issue by batselem** [Lornatang/RFB_ESRGAN-PyTorch#6]
I got the following error when I run test_image.py on a test image

COMMAND:
`E:\Projects\RFB_ESRGAN-PyTorch>python test_image.py -a rfb --lr E:/Projects/ESRGAN/LR/baboon.png --pretrained --gpu 0`

RESULT:
```
##################################################

Run Testing Engine.

[ WARNING ] Directory `E:\Projects\RFB_ESRGAN-PyTorch\tests` already exists!
[ INFO ] TestingEngine:
        API version .......... 0.2.0
        Build ................ 2021.04.15
##################################################

[ INFO ] Using pre-trained model `rfb`.
Traceback (most recent call last):
  File "test_image.py", line 136, in <module>
    main()
  File "test_image.py", line 68, in main
    main_worker(args.gpu, args)
  File "test_image.py", line 77, in main_worker
    model = configure(args)
  File "E:\Projects\RFB_ESRGAN-PyTorch\rfb_esrgan_pytorch\utils\common.py", line 48, in configure
    model = models.__dict__[args.arch](pretrained=True)
  File "E:\Projects\RFB_ESRGAN-PyTorch\rfb_esrgan_pytorch\models\generator.py", line 122, in rfb
    return _gan("rfb", 16, pretrained, progress)
  File "E:\Projects\RFB_ESRGAN-PyTorch\rfb_esrgan_pytorch\models\generator.py", line 100, in _gan
    state_dict = load_state_dict_from_url(model_urls[arch], progress=progress, map_location=torch.device("cpu"))
  File "E:\Programs\Anaconda3\envs\yolact\lib\site-packages\torch\hub.py", line 517, in load_state_dict_from_url
    cached_file = os.path.join(model_dir, filename)
  File "E:\Programs\Anaconda3\envs\yolact\lib\ntpath.py", line 115, in join
    genericpath._check_arg_types('join', path, *paths)
  File "E:\Programs\Anaconda3\envs\yolact\lib\genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by Lornatang** [comment]
Sorry , `RFB_ESRGAN` not have pretrained weights.....
